import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ThemeProvider from "@/providers/ThemeProvider";
import { Suspense } from "react";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={true}
          disableTransitionOnChange
          enableColorScheme={true}
        >
          <Suspense>
            <Navbar />
            <main className="flex min-h-screen flex-col items-center justify-between p-24 mx-[1rem] lg:mx-[3rem] xl:mx-[7rem] 2xl:mx-[12rem]">
              {children}
            </main>
            <Footer />
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
